### ISSUE TITLE
Solve operator==, operator!= in allocators

### ISSUE THREAD

**Issue by Kejsty** [xlauko/pb173_project#6]
via http://en.cppreference.com/w/cpp/concept/Allocator : 
a1 == a2 returns true only if the storage allocated by the allocator a1 can be deallocated through a2. 

According to this, I suppose that NullAllocator always return true, Mallocator without std::set also. StackAllocator should be equal only to itself.
Should FallbackAllocator depend on its allocators?

**Comment by xtracko** [comment]
Fallback allocator return a.primary == b.primary && a.secondary == b.secondary
Stack allocator - compare the pointer of stack + assert(top == b.top)
Mallocator - return true
Freelist - a.root == b.root
Null allocator - return true

**Comment by xtracko** [comment]
Done
